language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- echo "test"
deploy:
    provider: pages
    local_dir: ../ak340.github.io/
    target_branch: master
    github_token: $GH_TOKEN
