language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make publish github
deploy:
	provider: pages
	local_dir: ../ak340.github.io/
	target-branch: master
	github_token: $GITHUB_TOKEN
