language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pelican-themes --install 
script:
- make html
deploy:
    provider: pages
    local_dir: ../ak340.github.io/
    target-branch: master
    github_token: $GITHUB_TOKEN
