language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- echo "test"
deploy:
    provider: pages
    skip_cleanup: true    
    target_branch: master
    github_token: $GH_TOKEN
    keep_history: true
    on:
	branch:master
