language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- git clone https://github.com/getpelican/pelican-themes ~/pelican-themes
- git clone https://github.com/alexandrevicenzi/Flex
- pelican-themes --install Flex/ --verbose
script:
- make publish

deploy:
   provider: pages
   repo: ak340/ak340.github.io
   email: travis-ci@domain.com
   name: Travis-CI
   commit_message: "Tested. Committing"
   target_branch: master
   skip_cleanup: true
   github_token: $GH_TOKEN
   local_dir: output
   edge: true
   on:
       branch: master
