language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make html
deploy:
   provider: pages
   repo:ak340/ak340.github.io
   target_branch: master
   skip_cleanup: true
   github_token: $GH_TOKEN
   local_dir: output
   on:
	branch: master
