language: python
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- echo "test"
deploy:
    provider: pages
    skip_cleanup: true    
    github_token: $GH_TOKEN
    keep_history: true
    edge: true
    on:
	branch: master
